[package]
name = "projet-s4"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk = "0.18"
glib = "0.18"
hound = "3.5.0"
rustfft = "6.1.0"
flate2 = "1.0"
once_cell = "1.19"
image = "0.24"
rodio = "0.14"
gdk-pixbuf = "0.20.9"
cairo = "0.0.4"

