[package]
name = "projet-s4"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk = "0.18"
glib = "0.18"
hound = "3.5.0"
rustfft = "6.1.0"
flate2 = "1.0"
gstreamer = "0.19"
gstreamer-audio = "0.19"
gstreamer-pbutils = "0.19"
once_cell = "1.19"
image = "0.24"

